apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagster
spec:
  chart:
    spec:
      version: ">=1.13.0 <1.14.0"
  values:
    dagsterWebserver:
      replicaCount: 2
    dagster-user-deployments:
      deployments:
        - name: dagster-pipelines
          image:
            tag: ~
            repository: "docker.io/dagster/user-code-example"
            pullPolicy: IfNotPresent
          replicaCount: 2
          port: 3030
