apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/dagster
  - ../base/backend-ci

patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo

  - path: dagster-values.yaml
    target:
      kind: HelmRelease

  - path: backend-ci/backend-ci-patch.yaml
    target:
      kind: Deployment
      name: backend-ci
