apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/dagster
  - ../base/backend-ci
  - ../base/ray
  - ../seaweedfs
  - backend-ci/backend-ci-image-updater.yaml
  - dagster/dagster-pipelines-image-updater.yaml

patches:
  - path: dagster/dagster-values.yaml
    target:
      kind: HelmRelease

  - path: backend-ci/backend-ci-patch.yaml
    target:
      kind: Deployment
      name: backend-ci
