apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  chart:
    spec:
      version: ">=5.4.0 <6.0.0"
  values:
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      size: 50Gi
      storageClass: ""
    resources:
      requests:
        cpu: 250m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
