apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/backend-ci

patches:
  - path: podinfo-values.yaml
    target:
      kind: HelmRelease
      name: podinfo
      
  - path: dagster-values.yaml
    target:
      kind: HelmRelease
      name: dagster
    
  - path: backend-ci-patch.yaml
    target:
      kind: Deployment
      name: backend-ci
